/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.NguoiDungDAO;
import Helper.AUTH;
import Helper.MsgBox;
import NhanVien.MainJFrame_user;
import Loand.MainLoading;
import QLCC.model.NguoiDung;
import QLCCAdmin.UI.MainJFrame;
import QRCode.Menu;
import java.awt.Color;

/**
 *
 * @author DELL
 */
public class Login_cuaTan extends javax.swing.JFrame {

    /**
     * Creates new form Login_cuaTan
     */
    public Login_cuaTan() {
        initComponents();
        setLocationRelativeTo(this);
        MainLoading mn =new MainLoading(this, rootPaneCheckingEnabled);
        mn.setVisible(true);
        txt_user.setBackground(new Color(0,0,0,1));
        txt_pass.setBackground(new Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_user.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        txt_user.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 330, 50));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 330, 60));

        txt_pass.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 330, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/qr-code.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 30, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Screenshot 2023-04-05 133913.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dangNhap();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Menu mn = new Menu();
        mn.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_cuaTan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_cuaTan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_cuaTan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_cuaTan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login_cuaTan lg = new Login_cuaTan();
                lg.setLocationRelativeTo(null);
                lg.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables

    private void dangNhap() {
        NguoiDungDAO dao = new NguoiDungDAO();
        String manv = txt_user.getText();
        String matkhau = new String(txt_pass.getPassword());
        NguoiDung nv = dao.selectById(manv);
        if (manv.length() == 0 || matkhau.length() == 0) {
            MsgBox.alert(this, "Không được để trống !");
            return;
        } else if (nv == null) {
            MsgBox.alert(this, "Sai tên đăng nhập !");
            return;
        } else if ((!matkhau.equals(nv.getMatKhau()))) {
            MsgBox.alert(this, "Sai mật khẩu !");
            return;
        } else if (nv.isChucVu()==true) {
            AUTH.user = nv;
            new MainJFrame().setVisible(true);
        }
        else 
        {
            AUTH.user = nv;
            MainJFrame_user mj = new MainJFrame_user();
            mj.setVisible(true);
        }
        System.out.println(nv.isChucVu());
    }
}
